# Numpy basics

In [1]:
import numpy as np
print(np.__version__)

2.5.0


# NumPy Fundamentals

NumPy (Numerical Python) is the fundamental library used for numerical computing in Python.

It provides:

- Fast multidimensional arrays
- Mathematical operations
- Matrix computations
- Linear algebra
- Random number generation
- Foundation for Machine Learning, Data Science and Deep Learning

Almost every AI library (Pandas, Scikit-Learn, TensorFlow, PyTorch) internally uses NumPy.

## Why not Python Lists?

Python lists are flexible but slow for numerical computation.

NumPy arrays:

- consume less memory
- execute faster
- support vectorized operations
- are optimized using C

## Creating a NumPy Array

The np.array() function is used to create a NumPy array from Python lists.

Syntax:

np.array(iterable)

In [2]:
import numpy as np
arr = np.array([10,20,20,40])
print(arr)

[10 20 20 40]


In [3]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([1.5,2.5,3.5])
arr3 = np.array(["Apple, Banana, Mango"])
arr4 = np.array([True, False, True])

print(arr1)
print(arr2)
print(arr3)
print(arr4)

[1 2 3]
[1.5 2.5 3.5]
['Apple, Banana, Mango']
[ True False  True]


# Array Attributes

Every NumPy array stores metadata (information about the array).

Array attributes help us understand:

- Number of dimensions
- Shape of the array
- Total number of elements
- Data type of elements
- Memory occupied by each element
- Total memory occupied by the array

These attributes are useful for debugging, data analysis, and Machine Learning.

In [4]:
import numpy as np

arr = np.array([[10, 20, 30],
                [40, 50, 60]])

print(arr)

[[10 20 30]
 [40 50 60]]


## ndim

`ndim` returns the number of dimensions (axes) of an array.

Examples:

- 1D array → ndim = 1
- 2D array → ndim = 2
- 3D array → ndim = 3

In [5]:
print(arr.ndim)

2


## shape

`shape` returns the size of each dimension.

Output is returned as a tuple.

For a 2D array:

(rows, columns)

In [6]:
print(arr.shape)

(2, 3)


## size

`size` returns the total number of elements present in the array.

In [7]:
print(arr.size)

6


## dtype

`dtype` returns the data type of the elements stored in the array.

In [8]:
print(arr.dtype)

int64


## itemsize

`itemsize` returns the memory occupied by one element (in bytes).

In [9]:
print(arr.itemsize)

8


## nbytes

`nbytes` returns the total memory occupied by the array.

Formula:

Total Memory = size × itemsize

In [10]:
print(arr.nbytes)

48


In [11]:
import numpy as np

arr = np.array([[10, 20, 30],
                [40, 50, 60]])

print("Dimensions :", arr.ndim)
print("Shape      :", arr.shape)
print("Size       :", arr.size)
print("Data Type  :", arr.dtype)
print("Item Size  :", arr.itemsize)
print("Total Bytes:", arr.nbytes)

Dimensions : 2
Shape      : (2, 3)
Size       : 6
Data Type  : int64
Item Size  : 8
Total Bytes: 48


# Array Creation Functions

NumPy provides several built-in functions to create arrays efficiently.

Instead of manually entering values, these functions allow us to generate arrays with predefined values, sequences, or matrix structures.

Common array creation functions:

- np.zeros()
- np.ones()
- np.full()
- np.empty()
- np.arange()
- np.linspace()
- np.eye()
- np.identity()
- np.diag()

## np.zeros()

The `np.zeros()` function creates an array filled with zeros.

By default, the elements are of floating-point type (`float64`).

### Syntax

np.zeros(shape, dtype=float)

Parameters:
- shape → Size of the array (integer or tuple)
- dtype → Data type of the array (optional)

Returns:
A NumPy array filled with zeros.

In [1]:
import numpy as np

arr = np.zeros(5)

print(arr)

[0. 0. 0. 0. 0.]


In [2]:
arr = np.zeros((3,4))

print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
arr = np.zeros((2,3), dtype=int)

print(arr)

[[0 0 0]
 [0 0 0]]


Normally zeros() creates float values.

Using dtype=int creates integer zeros.

In [4]:
arr = np.zeros((2,3), dtype = bool)

print(arr)

[[False False False]
 [False False False]]


## np.ones()

The `np.ones()` function creates an array filled with ones.

By default, all elements are of floating-point type (`float64`).

### Syntax

np.ones(shape, dtype=float)

Parameters:
- shape → Size of the array (integer or tuple)
- dtype → Data type of the array (optional)

Returns:
A NumPy array filled with ones.

In [5]:
arr = np.ones(5)

print(arr)

[1. 1. 1. 1. 1.]


In [6]:
arr = np.ones((2, 4))

print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
arr = np.ones((3, 3), dtype=int)

print(arr)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


## np.full()

The `np.full()` function creates an array of a specified shape, where every element is filled with the same value.

### Syntax

np.full(shape, fill_value, dtype=None)

Parameters:
- shape → Size of the array (integer or tuple)
- fill_value → Value to fill the array with
- dtype → Data type of the array (optional)

Returns:
A NumPy array filled with the specified value.

In [8]:
arr = np.full(5, 7)

print(arr)

[7 7 7 7 7]


In [9]:
arr = np.full((2, 3), 9)

print(arr)

[[9 9 9]
 [9 9 9]]


In [10]:
arr = np.full((2, 2), 3.14, dtype=float)

print(arr)

[[3.14 3.14]
 [3.14 3.14]]


## np.empty()

The `np.empty()` function creates an array without initializing its elements.

Unlike `np.zeros()` or `np.ones()`, the values stored in the array are whatever already exists in the allocated memory.

The contents of the array are unpredictable and should not be relied upon.

### Syntax

np.empty(shape, dtype=float)

Parameters:
- shape → Size of the array (integer or tuple)
- dtype → Data type of the array (optional)

Returns:
An uninitialized NumPy array.

In [11]:
arr = np.empty(5)

print(arr)

[3.5e-323 3.5e-323 3.5e-323 3.5e-323 3.5e-323]


In [12]:
arr = np.empty((2, 3))

print(arr)

[[4.4e-323 4.4e-323 4.4e-323]
 [4.4e-323 4.4e-323 4.4e-323]]


In [13]:
arr = np.empty((2, 3))

arr.fill(5)

print(arr)

[[5. 5. 5.]
 [5. 5. 5.]]


## np.arange()

The `np.arange()` function creates an array with evenly spaced values within a specified range.

It works similarly to Python's built-in `range()` function, but returns a NumPy array instead of a range object.

### Syntax

np.arange([start,] stop[, step], dtype=None)

Parameters:
- start → Starting value (default = 0)
- stop → Ending value (not included)
- step → Difference between consecutive values (default = 1)
- dtype → Data type of the array (optional)

Returns:
A NumPy array containing evenly spaced values.

In [14]:
arr = np.arange(5)

print(arr)

[0 1 2 3 4]


In [15]:
arr = np.arange(2, 8)

print(arr)

[2 3 4 5 6 7]


In [16]:
arr = np.arange(0, 10, 2)

print(arr)

[0 2 4 6 8]


In [17]:
arr = np.arange(10, 0, -2)

print(arr)

[10  8  6  4  2]


## np.linspace()

The `np.linspace()` function creates an array of evenly spaced values between a specified start and stop value.

Unlike `np.arange()`, you specify the **number of values** to generate instead of the step size.

By default, the stop value is included.

### Syntax

np.linspace(start, stop, num=50, endpoint=True, dtype=None)

Parameters:
- start → Starting value
- stop → Ending value
- num → Number of values to generate (default = 50)
- endpoint → Whether to include the stop value (default = True)
- dtype → Data type of the array (optional)

Returns:
A NumPy array containing evenly spaced values.

In [18]:
arr = np.linspace(1, 10, 5)

print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


In [19]:
arr = np.linspace(0, 10, 5, endpoint=False)

print(arr)

[0. 2. 4. 6. 8.]


In [20]:
arr = np.linspace(1, 10, 5, dtype=int)

print(arr)

[ 1  3  5  7 10]


## np.eye()

The `np.eye()` function creates a 2D array with ones on the main diagonal and zeros elsewhere.

It is commonly used to create an identity-like matrix.

### Syntax

np.eye(N, M=None, k=0, dtype=float)

Parameters:
- N → Number of rows
- M → Number of columns (optional, default = N)
- k → Index of the diagonal (default = 0)
- dtype → Data type (optional)

Returns:
A 2D NumPy array.

In [21]:
arr = np.eye(3)

print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
arr = np.eye(3, 4)

print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


## np.identity()

The `np.identity()` function creates a square identity matrix.

An identity matrix has ones on the main diagonal and zeros elsewhere.

### Syntax

np.identity(n, dtype=None)

Parameter:
- n → Size of the square matrix

Returns:
A square identity matrix.

In [23]:
arr = np.identity(4)

print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## np.diag()

The `np.diag()` function is used to create a diagonal matrix from a 1D array or extract the diagonal elements from a 2D array.

### Syntax

np.diag(v, k=0)

In [24]:
arr = np.diag([2, 4, 6, 8])

print(arr)

[[2 0 0 0]
 [0 4 0 0]
 [0 0 6 0]
 [0 0 0 8]]


In [25]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print(np.diag(matrix))

[1 5 9]


## NumPy Data Types

Every element in a NumPy array has a specific data type (`dtype`).

The data type determines:
- What kind of values the array can store.
- How much memory each element occupies.
- How numerical operations are performed.

Common NumPy data types include:

- int
- float
- bool
- str

NumPy also provides specific data types such as:
- int32
- int64
- float32
- float64

In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4])

print(arr)
print(arr.dtype)

[1 2 3 4]
int64


In [3]:
arr = np.array([1.5, 2.8, 3.2])

print(arr)
print(arr.dtype)

[1.5 2.8 3.2]
float64


In [4]:
arr = np.array([True, False, True])

print(arr)
print(arr.dtype)

[ True False  True]
bool


In [5]:
arr = np.array(["Apple", "Banana", "Mango"])

print(arr)
print(arr.dtype)

['Apple' 'Banana' 'Mango']
<U6


In [6]:
arr = np.array([1, 2.5, 3])

print(arr)
print(arr.dtype)

[1.  2.5 3. ]
float64


## dtype Parameter

The `dtype` parameter is used to specify the data type of the elements while creating a NumPy array.

Instead of allowing NumPy to choose the data type automatically, you can explicitly define it.

### Syntax

np.array(object, dtype=data_type)

Common data types:
- int
- float
- bool
- str
- int32
- int64
- float32
- float64

In [7]:
arr = np.array([1, 2, 3], dtype=float)

print(arr)
print(arr.dtype)

[1. 2. 3.]
float64


In [8]:
arr = np.array([1.8, 2.9, 3.1], dtype=int)

print(arr)
print(arr.dtype)

[1 2 3]
int64


In [9]:
arr = np.array([1, 0, 5, 0], dtype=bool)

print(arr)
print(arr.dtype)

[ True False  True False]
bool


In [10]:
arr = np.array([10, 20, 30], dtype=str)

print(arr)
print(arr.dtype)

['10' '20' '30']
<U2


## astype()

The `astype()` method is used to convert the data type of an existing NumPy array.

Unlike the `dtype` parameter, which specifies the data type while creating an array, `astype()` changes the data type after the array has already been created.

### Syntax

array.astype(new_data_type)

Returns:
A new NumPy array with the specified data type.

In [11]:
arr = np.array([1, 2, 3])

new_arr = arr.astype(float)

print(arr)
print(new_arr)

print(arr.dtype)
print(new_arr.dtype)

[1 2 3]
[1. 2. 3.]
int64
float64


In [12]:
arr = np.array([1.8, 2.9, 3.5])

new_arr = arr.astype(int)

print(new_arr)

[1 2 3]


In [13]:
arr = np.array([10, 20, 30])

new_arr = arr.astype(str)

print(new_arr)
print(new_arr.dtype)

['10' '20' '30']
<U21


In [14]:
arr = np.array([0, 1, 5, 0])

new_arr = arr.astype(bool)

print(new_arr)

[False  True  True False]


In [15]:
arr = np.array([1, 2, 3])

new_arr = arr.astype(float)

print(arr.dtype)
print(new_arr.dtype)

int64
float64


# IMPORTANT QUESTIONS

## Why not Python Lists?

Python lists are flexible but slow for numerical computation.

NumPy arrays:

- consume less memory
- execute faster
- support vectorized operations
- are optimized using C

Q1. Difference between shape and size?

shape → Dimensions of the array (rows, columns, ...)
size → Total number of elements

Q2. What does ndim return?

The number of dimensions (axes) in the array.

Q3. What is dtype?

It tells us the data type of the elements stored in the NumPy array.

Q4. Why does np.zeros() return floats by default?

Answer:

Because the default value of the dtype parameter is float (float64 on most systems). You can change it using the dtype argument.

Q5. What is the difference between np.zeros() and np.ones()?

Answer:

np.zeros() creates an array filled with 0s.
np.ones() creates an array filled with 1s.
Both accept the same parameters: shape and optional dtype.

Q6. When should you use np.full() instead of np.zeros() or np.ones()?

Answer:

Use np.full() when you want every element of the array to have the same custom value, such as 5, -1, or 3.14.

Q7. Is np.empty() actually empty?

Answer:

No. It only allocates memory without initializing the elements. The array contains whatever values were already present in that memory location. np.empty() can be slightly faster than np.zeros() because it skips initialization.

It is useful when you know you'll immediately overwrite every element. Otherwise, prefer zeros() or full() for predictable values.

Q8.
| `range()`                       | `np.arange()`                  |
| ------------------------------- | ------------------------------ |
| Returns a range object          | Returns a NumPy array          |
| Used in Python loops            | Used for numerical computing   |
| Limited mathematical operations | Supports vectorized operations |


Q9.
| `np.arange()`              | `np.linspace()`                                  |
| -------------------------- | ------------------------------------------------ |
| Specify **step size**      | Specify **number of values**                     |
| Stop value is excluded     | Stop value is included (default)                 |
| Good for integer sequences | Good for evenly spaced values, especially floats |


Q10. When should you use np.linspace() instead of np.arange()?

Answer:

Use np.linspace() when you know how many values you want between two points, especially for floating-point data.

Use np.arange() when you know the step size.

Q11.
| Function        | You Control          |
| --------------- | -------------------- |
| `np.arange()`   | **Step size**        |
| `np.linspace()` | **Number of values** |

arange() → "Mujhe har 2 step pe value chahiye."
linspace() → "Mujhe total 10 values chahiye."

Q12. 
| `np.eye()`                      | `np.identity()`              |
| ------------------------------- | ---------------------------- |
| Can create rectangular matrices | Creates only square matrices |
| More flexible                   | Simpler                      |


Q13. Can a NumPy array store multiple data types?

Answer:

No. A NumPy array stores only one data type. If multiple types are provided, NumPy converts them to a common compatible type automatically.

Q14. What is the purpose of the dtype parameter?

Answer:

The dtype parameter is used to explicitly specify the data type of the array elements during array creation.

Q15. 
| `dtype`                               | `astype()`                      |
| ------------------------------------- | ------------------------------- |
| Used while creating an array          | Used after the array is created |
| Sets the initial data type            | Converts an existing array      |
| Example: `np.array(..., dtype=float)` | Example: `arr.astype(float)`    |


Q16. astype() returns a new array and does not modify the original array.