
# Indexing & Slicing

Topics Covered

- Indexing
- Negative Indexing
- Slicing
- 2D Arrays
- 3D Arrays
- Fancy Indexing
- Boolean Indexing
- Views vs Copies

# Indexing in NumPy

## What is Indexing?

Indexing is the process of accessing a specific element of an array using its position (index).

Python follows **0-based indexing**, meaning the first element has index 0.

First index = 0

Last Index = Length − 1

Syntax: array[index]

Invalid index gives IndexError.

Example:

Array:
[10, 20, 30, 40, 50]

Index:
 0   1   2   3   4

In [1]:
import numpy as np

arr = np.array([10,20,30,40,50])

print(arr)

print(arr[0])

[10 20 30 40 50]
10


# Negative Indexing

Negative indexing allows us to access elements from the end of an array.

Instead of counting from the beginning, Python counts from the last element.

Last element → -1, Second last → -2, First element → -Length

Syntax: array[-index]

Index Representation

Positive Index

 0   1   2   3   4
10  20  30  40  50

Negative Index

-5  -4  -3  -2  -1
10  20  30  40  50

Negative indexing is useful when we want to access elements from the end without knowing the array length.

In [2]:
import numpy as np

arr = np.array([10,20,30,40,50])

arr

array([10, 20, 30, 40, 50])

In [3]:
print(arr[-1])

50


# Slicing in NumPy

## What is Slicing?

Slicing is used to access multiple consecutive elements from an array.

Instead of retrieving a single element, slicing returns a portion (sub-array) of the original array.

### Syntax

array[start : stop : step]

where,

- start → Starting index (included)
- stop → Ending index (excluded)
- step → Number of elements to skip (default = 1)

Important Rule:

Start is included.
Stop is excluded.

In [4]:
import numpy as np

arr = np.array([10,20,30,40,50])

arr

array([10, 20, 30, 40, 50])

In [5]:
arr[1:4]

array([20, 30, 40])

# Step Slicing

## What is Step Slicing?

Step slicing allows us to skip elements while creating a slice.

### Syntax

array[start : stop : step]

where,

- start → Starting index (included)
- stop → Ending index (excluded)
- step → Number of positions to move after selecting an element

Default value of step is 1.

Positive step moves from left to right.

Negative step moves from right to left.

In [6]:
import numpy as np

arr = np.array([10,20,30,40,50,60,70,80])

arr

array([10, 20, 30, 40, 50, 60, 70, 80])

In [7]:
arr[0:8:1]

array([10, 20, 30, 40, 50, 60, 70, 80])

In [8]:
arr[0:8:2]

array([10, 30, 50, 70])

In [9]:
arr[1:8:2]

array([20, 40, 60, 80])

In [10]:
arr[2:7:3]

array([30, 60])

In [11]:
arr[::2]

array([10, 30, 50, 70])

In [12]:
arr[1::2]

array([20, 40, 60, 80])

# Negative Step Slicing

## What is Negative Step?

A negative step allows us to traverse an array from right to left.

Instead of moving forward, Python moves backward.

### Syntax

array[start : stop : step]

where,

- start → Starting index
- stop → Ending index (excluded)
- step → Negative value (moves backward)

Common Examples

[::-1] → Reverse the array

[::-2] → Every second element from the end

In [13]:
import numpy as np

arr = np.array([10,20,30,40,50,60,70,80])

arr

array([10, 20, 30, 40, 50, 60, 70, 80])

In [14]:
arr[::-1]

array([80, 70, 60, 50, 40, 30, 20, 10])

In [15]:
arr[::-2]

array([80, 60, 40, 20])

In [16]:
arr[6:1:-1]

array([70, 60, 50, 40, 30])

In [17]:
arr[5:0:-2]

array([60, 40, 20])

# 2D Array Indexing

## What is a 2D Array?

A 2D array is an array of arrays.

It consists of rows and columns and is commonly used to represent tables, matrices, images, and datasets.

### Syntax

array[row_index, column_index]

Important:

- First index → Row
- Second index → Column

In [18]:
import numpy as np

arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [19]:
print(arr[0,0])

10


In [20]:
arr[1,2]

np.int64(60)

In [21]:
arr[1]

array([40, 50, 60])

# 2D Array Slicing

## What is 2D Slicing?

2D slicing is used to access multiple rows and multiple columns from a 2D array.

Unlike 1D slicing, we specify slicing separately for rows and columns.

### Syntax

array[row_slice, column_slice]

where,

- row_slice → Selects rows
- column_slice → Selects columns

General Form

array[row_start : row_stop : row_step,
      col_start : col_stop : col_step]

In [22]:
import numpy as np

arr = np.array([
    [11,12,13,14],
    [21,22,23,24],
    [31,32,33,34],
    [41,42,43,44]
])

arr

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [23]:
arr[1:3]

array([[21, 22, 23, 24],
       [31, 32, 33, 34]])

In [24]:
arr[:,1]

array([12, 22, 32, 42])

In [25]:
arr[:,:]

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [26]:
arr[2,:]

array([31, 32, 33, 34])

In [27]:
arr[:,1:3]

array([[12, 13],
       [22, 23],
       [32, 33],
       [42, 43]])

In [28]:
arr[1:3,1:3]

array([[22, 23],
       [32, 33]])

In [29]:
arr[1:3,2]

array([23, 33])

# Advanced 2D Slicing

## What is Advanced 2D Slicing?

Advanced 2D slicing allows us to select rows and columns using step values and reverse directions.

It helps us efficiently extract patterns from datasets without using loops.

### Syntax

array[row_start : row_stop : row_step,
      col_start : col_stop : col_step]

Remember:

- First part → Rows
- Second part → Columns
- Step controls how many elements are skipped.
- Negative step reverses the direction.

In [30]:
import numpy as np

arr = np.array([
    [11,12,13,14],
    [21,22,23,24],
    [31,32,33,34],
    [41,42,43,44]
])

arr

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [31]:
arr[::2, :]

array([[11, 12, 13, 14],
       [31, 32, 33, 34]])

In [32]:
arr[:, ::2]

array([[11, 13],
       [21, 23],
       [31, 33],
       [41, 43]])

In [33]:
arr[::2, ::2]

array([[11, 13],
       [31, 33]])

In [34]:
arr[::-1, :]

array([[41, 42, 43, 44],
       [31, 32, 33, 34],
       [21, 22, 23, 24],
       [11, 12, 13, 14]])

In [35]:
arr[:, ::-1]

array([[14, 13, 12, 11],
       [24, 23, 22, 21],
       [34, 33, 32, 31],
       [44, 43, 42, 41]])

In [36]:
arr[::-1, ::-1]

array([[44, 43, 42, 41],
       [34, 33, 32, 31],
       [24, 23, 22, 21],
       [14, 13, 12, 11]])

# Boolean Indexing (Filtering)

## What is Boolean Indexing?

Boolean Indexing is a technique used to filter elements from an array based on a condition.

Instead of accessing elements using positions (indices), we access them using True and False values.

### Why is it Important?

- Data Filtering
- Data Cleaning
- Machine Learning
- Data Analysis
- Feature Selection

Boolean Indexing is one of the most frequently used NumPy concepts.

In [37]:
import numpy as np

arr = np.array([10,20,30,40,50])

print(arr)

[10 20 30 40 50]


In [38]:
arr>25

array([False, False,  True,  True,  True])

In [39]:
arr[arr>25]

array([30, 40, 50])

# Multiple Conditions in Boolean Indexing

## What are Multiple Conditions?

Sometimes, we need to filter data using more than one condition.

Examples:
- Marks greater than 40 AND less than 80
- Age greater than 18 OR Salary greater than 50000

NumPy provides special operators to combine multiple conditions.

### Operators

&  → AND

|  → OR

~  → NOT

⚠ Never use Python's `and`, `or`, and `not` with NumPy arrays.

In [40]:
import numpy as np

marks = np.array([25, 42, 58, 76, 89, 91, 35])

In [41]:
(marks > 40) & (marks < 90)

array([False,  True,  True,  True,  True, False, False])

In [42]:
marks[(marks > 40) & (marks < 90)]

array([42, 58, 76, 89])

In [43]:
marks[(marks < 40) | (marks > 90)]

array([25, 91, 35])

In [44]:
marks[~(marks >= 40)]

array([25, 35])

In [45]:
arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

In [46]:
arr[arr > 50]

array([60, 70, 80, 90])

# Fancy Indexing

## What is Fancy Indexing?

Fancy Indexing is a technique used to access multiple specific elements, rows, or columns at once using lists or arrays of indices.

Unlike slicing, Fancy Indexing allows us to choose any positions in any order.

### Why is it useful?

- Selecting specific samples
- Rearranging data
- Feature selection
- Machine Learning preprocessing

In [47]:
import numpy as np

arr = np.array([10,20,30,40,50])

In [48]:
arr[[0,3,4]]

array([10, 40, 50])

In [49]:
arr[[1,1,3]]

array([20, 20, 40])

In [50]:
arr = np.array([
    [11,12,13],
    [21,22,23],
    [31,32,33],
    [41,42,43]
])

In [51]:
arr[[0,2,3]]

array([[11, 12, 13],
       [31, 32, 33],
       [41, 42, 43]])

In [52]:
arr[[3,1,0]]

array([[41, 42, 43],
       [21, 22, 23],
       [11, 12, 13]])

In [53]:
arr[[-1,-3]]

array([[41, 42, 43],
       [21, 22, 23]])