
# Indexing & Slicing

Topics Covered

- Indexing
- Negative Indexing
- Slicing
- 2D Arrays
- 3D Arrays
- Fancy Indexing
- Boolean Indexing
- Views vs Copies

# Indexing in NumPy

## What is Indexing?

Indexing is the process of accessing a specific element of an array using its position (index).

Python follows **0-based indexing**, meaning the first element has index 0.

First index = 0

Last Index = Length − 1

Syntax: array[index]

Invalid index gives IndexError.

Example:

Array:
[10, 20, 30, 40, 50]

Index:
 0   1   2   3   4

In [4]:
import numpy as np

arr = np.array([10,20,30,40,50])

print(arr)

print(arr[0])

[10 20 30 40 50]
10


# Negative Indexing

Negative indexing allows us to access elements from the end of an array.

Instead of counting from the beginning, Python counts from the last element.

Last element → -1, Second last → -2, First element → -Length

Syntax: array[-index]

Index Representation

Positive Index

 0   1   2   3   4
10  20  30  40  50

Negative Index

-5  -4  -3  -2  -1
10  20  30  40  50

Negative indexing is useful when we want to access elements from the end without knowing the array length.

In [5]:
import numpy as np

arr = np.array([10,20,30,40,50])

arr

array([10, 20, 30, 40, 50])

In [7]:
print(arr[-1])

50


# Slicing in NumPy

## What is Slicing?

Slicing is used to access multiple consecutive elements from an array.

Instead of retrieving a single element, slicing returns a portion (sub-array) of the original array.

### Syntax

array[start : stop : step]

where,

- start → Starting index (included)
- stop → Ending index (excluded)
- step → Number of elements to skip (default = 1)

Important Rule:

Start is included.
Stop is excluded.

In [5]:
import numpy as np

arr = np.array([10,20,30,40,50])

arr

array([10, 20, 30, 40, 50])

In [6]:
arr[1:4]

array([20, 30, 40])

# Step Slicing

## What is Step Slicing?

Step slicing allows us to skip elements while creating a slice.

### Syntax

array[start : stop : step]

where,

- start → Starting index (included)
- stop → Ending index (excluded)
- step → Number of positions to move after selecting an element

Default value of step is 1.

Positive step moves from left to right.

Negative step moves from right to left.

In [7]:
import numpy as np

arr = np.array([10,20,30,40,50,60,70,80])

arr

array([10, 20, 30, 40, 50, 60, 70, 80])

In [8]:
arr[0:8:1]

array([10, 20, 30, 40, 50, 60, 70, 80])

In [9]:
arr[0:8:2]

array([10, 30, 50, 70])

In [10]:
arr[1:8:2]

array([20, 40, 60, 80])

In [11]:
arr[2:7:3]

array([30, 60])

In [12]:
arr[::2]

array([10, 30, 50, 70])

In [13]:
arr[1::2]

array([20, 40, 60, 80])

# Negative Step Slicing

## What is Negative Step?

A negative step allows us to traverse an array from right to left.

Instead of moving forward, Python moves backward.

### Syntax

array[start : stop : step]

where,

- start → Starting index
- stop → Ending index (excluded)
- step → Negative value (moves backward)

Common Examples

[::-1] → Reverse the array

[::-2] → Every second element from the end

In [14]:
import numpy as np

arr = np.array([10,20,30,40,50,60,70,80])

arr

array([10, 20, 30, 40, 50, 60, 70, 80])

In [15]:
arr[::-1]

array([80, 70, 60, 50, 40, 30, 20, 10])

In [16]:
arr[::-2]

array([80, 60, 40, 20])

In [17]:
arr[6:1:-1]

array([70, 60, 50, 40, 30])

In [18]:
arr[5:0:-2]

array([60, 40, 20])

# 2D Array Indexing

## What is a 2D Array?

A 2D array is an array of arrays.

It consists of rows and columns and is commonly used to represent tables, matrices, images, and datasets.

### Syntax

array[row_index, column_index]

Important:

- First index → Row
- Second index → Column

In [19]:
import numpy as np

arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [21]:
print(arr[0,0])

10


In [22]:
arr[1,2]

np.int64(60)

In [23]:
arr[1]

array([40, 50, 60])

# 2D Array Slicing

## What is 2D Slicing?

2D slicing is used to access multiple rows and multiple columns from a 2D array.

Unlike 1D slicing, we specify slicing separately for rows and columns.

### Syntax

array[row_slice, column_slice]

where,

- row_slice → Selects rows
- column_slice → Selects columns

General Form

array[row_start : row_stop : row_step,
      col_start : col_stop : col_step]

In [24]:
import numpy as np

arr = np.array([
    [11,12,13,14],
    [21,22,23,24],
    [31,32,33,34],
    [41,42,43,44]
])

arr

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [25]:
arr[1:3]

array([[21, 22, 23, 24],
       [31, 32, 33, 34]])

In [26]:
arr[:,1]

array([12, 22, 32, 42])

In [27]:
arr[:,:]

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [28]:
arr[2,:]

array([31, 32, 33, 34])

In [29]:
arr[:,1:3]

array([[12, 13],
       [22, 23],
       [32, 33],
       [42, 43]])

In [30]:
arr[1:3,1:3]

array([[22, 23],
       [32, 33]])

In [31]:
arr[1:3,2]

array([23, 33])