In [2]:
import numpy as np

# Notebook 3 - NumPy Operations & Broadcasting

## 🎯 Objective

In this notebook, we will learn how to perform mathematical operations on NumPy arrays efficiently.

We'll also understand one of NumPy's most powerful concepts—**Broadcasting**, which allows operations between arrays of different shapes without writing loops.

---

## 📚 Topics Covered

- Arithmetic Operations
- Scalar Operations
- Universal Functions (ufuncs)
- Aggregation Functions
- Axis Parameter
- Comparison Operations
- Boolean Masking
- Fancy Indexing
- Broadcasting

---

## 🤖 AI/ML Connection

Almost every Machine Learning and Deep Learning algorithm performs millions of mathematical operations on data.

Examples include:

- Feature Scaling
- Image Brightness Adjustment
- Neural Network Weight Updates
- Loss Calculation
- Gradient Descent
- Data Normalization

NumPy makes these operations extremely fast.

# 1️⃣ Arithmetic Operations

## What are Arithmetic Operations?

Arithmetic operations are basic mathematical operations such as addition, subtraction, multiplication, division, modulus, floor division, and exponentiation.

Unlike Python lists, NumPy performs these operations **element-wise**.

This means that the operation is performed on corresponding elements of two arrays.

---

## Why is this Important?

Imagine you have a dataset containing one million values.

Using Python loops, performing operations on every value would take much longer.

NumPy performs these operations internally using optimized C code, making them significantly faster.

---

## Real-Life Example

Suppose you have marks of students in two tests.

Test 1

[80, 75, 90]

Test 2

[10, 15, 5]

If bonus marks need to be added:

80 + 10

75 + 15

90 + 5

NumPy performs this automatically without writing loops.

In [3]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Array A :", a)
print("Array B :", b)

Array A : [1 2 3]
Array B : [4 5 6]


## Addition

Addition combines corresponding elements from both arrays.

This is called **Element-wise Addition**.

Formula

Result[i] = A[i] + B[i]

In [4]:
a + b

array([5, 7, 9])

# 2️⃣ Subtraction

## What is Subtraction?

Subtraction means finding the difference between corresponding elements of two NumPy arrays.

Like addition, NumPy performs subtraction **element-wise**.

It subtracts each element of the second array from the element at the same position in the first array.

---

## Formula

Result[i] = A[i] - B[i]

---

## Why is it Useful?

Subtraction is widely used in:

- Finding errors (Predicted - Actual)
- Data preprocessing
- Calculating differences between datasets
- Image processing (finding changes between two images)
- Machine Learning loss calculations

In [7]:
a = np.array([10, 20, 30])
b = np.array([4, 5, 6])

a - b

array([ 6, 15, 24])

In [8]:
b-a

array([ -6, -15, -24])

### Important Observation

Changing the order of arrays changes the answer.

A - B ≠ B - A

Therefore, subtraction is **not commutative**.

# 3️⃣ Multiplication

## What is Multiplication?

NumPy multiplies corresponding elements of two arrays.

This is called **Element-wise Multiplication**.

---

## Formula

Result[i] = A[i] × B[i]

---

## ⚠️ Important

Many beginners think that using `*` performs Matrix Multiplication.

This is incorrect.

In NumPy:

`*` → Element-wise Multiplication

`@` or `np.dot()` → Matrix Multiplication

In [9]:
a = np.array([2,4,6])
b = np.array([3,5,7])

a * b

array([ 6, 20, 42])

# 4️⃣ Division

NumPy divides corresponding elements.

Formula

Result[i] = A[i] / B[i]

The result of `/` is usually a floating-point number, even if both arrays contain integers.

In [10]:
a = np.array([10,20,30])
b = np.array([2,5,6])

a / b

array([5., 4., 5.])

# 5️⃣ Floor Division

Floor Division returns the quotient after removing the decimal part.

Operator

//

In [11]:
a = np.array([10,20,30])

b = np.array([3,6,7])

a // b

array([3, 3, 4])

# 6️⃣ Modulus

Modulus returns the remainder after division.

Operator

%

In [12]:
a = np.array([10,20,30])

b = np.array([3,6,7])

a % b

array([1, 2, 2])

# 7️⃣ Exponentiation

Exponentiation raises every element of an array to the specified power.

Operator

**

In [13]:
a = np.array([2,3,4])

a ** 2

array([ 4,  9, 16])

# 2️⃣ Scalar Operations

## What is a Scalar?

A **Scalar** is a single numerical value.

Examples:

5
10
-3
0
2.5

Unlike arrays, a scalar contains only one value.

---

## What are Scalar Operations?

Scalar operations mean performing an arithmetic operation between:

• One NumPy Array

and

• One Single Number (Scalar)

NumPy automatically applies the operation to **every element** of the array.

No loop is required.

In [14]:
a = np.array([1,2,3])

a

array([1, 2, 3])

In [15]:
a + 5

array([6, 7, 8])

### Explanation

NumPy automatically applies the scalar value to every element of the array.

Internally, NumPy performs the operation on each element.

Conceptually:

1 + 5

2 + 5

3 + 5

↓

[6,7,8]

The important thing is that **you do not have to write the loop yourself**.

In [16]:
a - 2

array([-1,  0,  1])

In [17]:
a * 10

array([10, 20, 30])

In [18]:
a / 2

array([0.5, 1. , 1.5])

In [19]:
a ** 3

array([ 1,  8, 27])