In [2]:
import numpy as np

# Notebook 3 - NumPy Operations & Broadcasting

## 🎯 Objective

In this notebook, we will learn how to perform mathematical operations on NumPy arrays efficiently.

We'll also understand one of NumPy's most powerful concepts—**Broadcasting**, which allows operations between arrays of different shapes without writing loops.

---

## 📚 Topics Covered

- Arithmetic Operations
- Scalar Operations
- Universal Functions (ufuncs)
- Aggregation Functions
- Axis Parameter
- Comparison Operations
- Boolean Masking
- Fancy Indexing
- Broadcasting

---

## 🤖 AI/ML Connection

Almost every Machine Learning and Deep Learning algorithm performs millions of mathematical operations on data.

Examples include:

- Feature Scaling
- Image Brightness Adjustment
- Neural Network Weight Updates
- Loss Calculation
- Gradient Descent
- Data Normalization

NumPy makes these operations extremely fast.

# 1️⃣ Arithmetic Operations

## What are Arithmetic Operations?

Arithmetic operations are basic mathematical operations such as addition, subtraction, multiplication, division, modulus, floor division, and exponentiation.

Unlike Python lists, NumPy performs these operations **element-wise**.

This means that the operation is performed on corresponding elements of two arrays.

---

## Why is this Important?

Imagine you have a dataset containing one million values.

Using Python loops, performing operations on every value would take much longer.

NumPy performs these operations internally using optimized C code, making them significantly faster.

---

## Real-Life Example

Suppose you have marks of students in two tests.

Test 1

[80, 75, 90]

Test 2

[10, 15, 5]

If bonus marks need to be added:

80 + 10

75 + 15

90 + 5

NumPy performs this automatically without writing loops.

In [3]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Array A :", a)
print("Array B :", b)

Array A : [1 2 3]
Array B : [4 5 6]


## Addition

Addition combines corresponding elements from both arrays.

This is called **Element-wise Addition**.

Formula

Result[i] = A[i] + B[i]

In [4]:
a + b

array([5, 7, 9])

# 2️⃣ Subtraction

## What is Subtraction?

Subtraction means finding the difference between corresponding elements of two NumPy arrays.

Like addition, NumPy performs subtraction **element-wise**.

It subtracts each element of the second array from the element at the same position in the first array.

---

## Formula

Result[i] = A[i] - B[i]

---

## Why is it Useful?

Subtraction is widely used in:

- Finding errors (Predicted - Actual)
- Data preprocessing
- Calculating differences between datasets
- Image processing (finding changes between two images)
- Machine Learning loss calculations

In [7]:
a = np.array([10, 20, 30])
b = np.array([4, 5, 6])

a - b

array([ 6, 15, 24])

In [8]:
b-a

array([ -6, -15, -24])

### Important Observation

Changing the order of arrays changes the answer.

A - B ≠ B - A

Therefore, subtraction is **not commutative**.

# 3️⃣ Multiplication

## What is Multiplication?

NumPy multiplies corresponding elements of two arrays.

This is called **Element-wise Multiplication**.

---

## Formula

Result[i] = A[i] × B[i]

---

## ⚠️ Important

Many beginners think that using `*` performs Matrix Multiplication.

This is incorrect.

In NumPy:

`*` → Element-wise Multiplication

`@` or `np.dot()` → Matrix Multiplication

In [9]:
a = np.array([2,4,6])
b = np.array([3,5,7])

a * b

array([ 6, 20, 42])

# 4️⃣ Division

NumPy divides corresponding elements.

Formula

Result[i] = A[i] / B[i]

The result of `/` is usually a floating-point number, even if both arrays contain integers.

In [10]:
a = np.array([10,20,30])
b = np.array([2,5,6])

a / b

array([5., 4., 5.])

# 5️⃣ Floor Division

Floor Division returns the quotient after removing the decimal part.

Operator

//

In [11]:
a = np.array([10,20,30])

b = np.array([3,6,7])

a // b

array([3, 3, 4])

# 6️⃣ Modulus

Modulus returns the remainder after division.

Operator

%

In [12]:
a = np.array([10,20,30])

b = np.array([3,6,7])

a % b

array([1, 2, 2])

# 7️⃣ Exponentiation

Exponentiation raises every element of an array to the specified power.

Operator

**

In [13]:
a = np.array([2,3,4])

a ** 2

array([ 4,  9, 16])

# 2️⃣ Scalar Operations

## What is a Scalar?

A **Scalar** is a single numerical value.

Examples:

5
10
-3
0
2.5

Unlike arrays, a scalar contains only one value.

---

## What are Scalar Operations?

Scalar operations mean performing an arithmetic operation between:

• One NumPy Array

and

• One Single Number (Scalar)

NumPy automatically applies the operation to **every element** of the array.

No loop is required.

In [14]:
a = np.array([1,2,3])

a

array([1, 2, 3])

In [15]:
a + 5

array([6, 7, 8])

### Explanation

NumPy automatically applies the scalar value to every element of the array.

Internally, NumPy performs the operation on each element.

Conceptually:

1 + 5

2 + 5

3 + 5

↓

[6,7,8]

The important thing is that **you do not have to write the loop yourself**.

In [16]:
a - 2

array([-1,  0,  1])

In [17]:
a * 10

array([10, 20, 30])

In [18]:
a / 2

array([0.5, 1. , 1.5])

In [19]:
a ** 3

array([ 1,  8, 27])

# 3️⃣ Universal Functions (ufuncs)

## What are Universal Functions?

Universal Functions (ufuncs) are built-in NumPy functions that perform operations on every element of an array.

Instead of writing loops, we simply call a NumPy function.

The function is automatically applied to each element.

---

## Why are ufuncs useful?

Suppose you want to calculate the square root of 1 million numbers.

Using Python loops would require processing each element manually.

NumPy ufuncs process the entire array efficiently using optimized C implementation.

This makes them much faster and easier to use.

---

## Examples of ufuncs

- np.sqrt()
- np.square()
- np.abs()
- np.exp()
- np.log()
- np.sin()
- np.cos()
- np.max()
- np.min()

We will learn the most commonly used ones in this notebook.

In [1]:
import numpy as np

a = np.array([1,4,9,16])

np.sqrt(a)

array([1., 2., 3., 4.])

# 4️⃣ Aggregation Functions

## What are Aggregation Functions?

Aggregation Functions combine multiple values of an array and return a summary value.

Instead of returning another array, they usually return **one final result**.

---

## Why are they called "Aggregation"?

The word **Aggregate** means:

"To collect many things and combine them into one."

NumPy aggregation functions collect information from all elements and produce a summarized output.

---

## Common Aggregation Functions

• np.sum()

• np.mean()

• np.max()

• np.min()

• np.std()

• np.var()

We'll understand each one step by step.

# np.sum()

`np.sum()` adds all the elements of an array and returns their total.

Formula

Total = a₁ + a₂ + a₃ + ... + aₙ

In [2]:
a = np.array([10,20,30,40])

np.sum(a)

np.int64(100)

# np.mean()

Mean is the Average of all elements.

Formula

Mean = Sum of Elements / Number of Elements

In [3]:
a = np.array([10,20,30,40])

np.mean(a)

np.float64(25.0)

In [4]:
a = np.array([10,50,7,80,35])

np.max(a)

np.int64(80)

In [5]:
np.min(a)

np.int64(7)

# Standard Deviation

Standard Deviation measures how spread out the data is from the mean.

Small Standard Deviation

↓

Values are close together.

Large Standard Deviation

↓

Values are spread far apart.

In [7]:
a = np.array([10,20,30,40])

print(np.std(a))

11.180339887498949


Variance is another measure of data spread.

Variance = (Standard Deviation)²

NumPy calculates it using:

np.var()

In [8]:
np.var(a)

np.float64(125.0)

# 5️⃣ Axis Parameter

## What is an Axis?

An **Axis** represents the direction along which NumPy performs an operation.

Many NumPy functions such as:

- np.sum()
- np.mean()
- np.max()
- np.min()

allow us to specify an axis.

Without an axis, NumPy performs the operation on the entire array.

With an axis, NumPy performs the operation along a particular direction.

---

## Why is Axis Important?

Most real-world datasets are not one-dimensional.

They usually have rows and columns.

The **axis parameter** helps us decide whether an operation should be performed:

- Row-wise
- Column-wise
- Entire Array

In [2]:
import numpy as np
arr = np.array([[1,2,3],
                [4,5,6]])

arr

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
np.sum(arr)

np.int64(21)

### Explanation

Since we did not specify an axis,

NumPy adds every element of the array.

1 + 2 + 3 + 4 + 5 + 6

↓

21

In [4]:
np.sum(arr, axis=0)

array([5, 7, 9])

### What happened?

For `axis = 0`,

NumPy moves **down each column** and performs the operation.

Column 1

1 + 4 = 5

Column 2

2 + 5 = 7

Column 3

3 + 6 = 9

Result

[5,7,9]

In [5]:
np.sum(arr, axis=1)

array([ 6, 15])

### What happened?

For `axis = 1`,

NumPy moves across each row.

Row 1

1 + 2 + 3 = 6

Row 2

4 + 5 + 6 = 15

Result

[6,15]

# 6️⃣ Comparison Operations

## What are Comparison Operations?

Comparison operations compare elements of an array with another array or a scalar value.

Instead of returning numbers,

NumPy returns **Boolean values**.

Boolean values are:

True

or

False

---

## Why are Comparison Operations Important?

Comparison operations help us answer questions like:

• Which students scored above 90?

• Which temperatures are below 0?

• Which pixel values are greater than 200?

• Which salaries are less than ₹50,000?

Instead of manually checking every value,

NumPy checks all elements automatically.

In [6]:
import numpy as np

marks = np.array([35,72,91,48,99])

marks > 50

array([False,  True,  True, False,  True])

### Explanation

NumPy compares each element with 50.

35 > 50

↓

False

----------------

72 > 50

↓

True

----------------

91 > 50

↓

True

----------------

48 > 50

↓

False

----------------

99 > 50

↓

True

Final Result

[False, True, True, False, True]

In [7]:
marks >= 72

array([False,  True,  True, False,  True])

In [8]:
marks < 50

array([ True, False, False,  True, False])

In [9]:
marks <= 48

array([ True, False, False,  True, False])

In [10]:
marks == 91

array([False, False,  True, False, False])

In [11]:
marks != 72

array([ True, False,  True,  True,  True])

# 7️⃣ Broadcasting

## What is Broadcasting?

Broadcasting is a mechanism used by NumPy that allows arrays of different but compatible shapes to perform arithmetic operations.

Instead of physically copying data,

NumPy intelligently adjusts the arrays so that element-wise operations become possible.

---

## Why is Broadcasting Needed?

Suppose we have an array containing marks of students.

We want to add 5 bonus marks to every student.

Without broadcasting, we would need to write a loop.

With broadcasting, NumPy performs the operation automatically.

Broadcasting makes code:

- Shorter
- Faster
- Easier to read

In [12]:
a = np.array([1,2,3])

a + 5

array([6, 7, 8])

# Broadcasting (Part 2)

## Can NumPy Add Arrays of Different Shapes?

The answer is:

**Yes, but only if their shapes are compatible.**

Broadcasting does **not** mean that every pair of different-shaped arrays can be added.

NumPy first checks whether the shapes are compatible.

If they are compatible:

✅ Operation is performed.

Otherwise:

❌ NumPy raises a ValueError.

In [13]:
a = np.array([1,2,3])

b = np.array([10])

a + b

array([11, 12, 13])

In [14]:
a = np.array([1,2,3])

b = np.array([10,20,30])

a+b

array([11, 22, 33])

# Broadcasting Rules

When NumPy performs operations on two arrays of different shapes, it compares their shapes.

The comparison starts from the **last dimension** (rightmost side).

For every dimension:

✅ The sizes are equal

OR

✅ One of them is 1

If either condition is satisfied, NumPy can broadcast that dimension.

Otherwise, broadcasting fails and NumPy raises a ValueError.

In [17]:
a = np.array([1,2,3])

b = np.array([10,20,30])

a+b

array([11, 22, 33])

In [18]:
a = np.array([1,2,3])

b = np.array([10])

a+b

array([11, 12, 13])

In [19]:
import numpy as np

a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([10,20,30])

print(a+b)

[[11 22 33]
 [14 25 36]]


In [20]:
a = np.array([[1],
              [2],
              [3]])

b = np.array([10,20,30])

print(a+b)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


## Finding the Output Shape

After confirming that broadcasting is possible:

For each dimension:

- If both sizes are equal → Result keeps that size.
- If one size is 1 → Result takes the larger size.

Examples:

3 and 3 → 3

1 and 5 → 5

2 and 1 → 2