# Array manipulation

# NumPy reshape()

The reshape() function is used to change the shape (dimensions) of an array
without changing its data.

Syntax:
array.reshape(new_shape)

Important:
- Number of elements must remain the same.
- reshape() creates a new view whenever possible.
- It does NOT randomly rearrange values.
- It only changes how NumPy looks at the same data.

In [1]:
import numpy as np

arr = np.arange(12)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [2]:
arr.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
arr.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [4]:
arr.reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

# reshape() with -1

NumPy allows one dimension to be specified as -1.

- NumPy automatically calculates that dimension.
- Only ONE dimension can be -1.
- The total number of elements must still remain the same.

Syntax:

arr.reshape(-1)
arr.reshape(2, -1)
arr.reshape(-1, 3)

In [6]:
arr.reshape(3, -1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
arr.reshape(-1, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
import numpy as np

arr = np.arange(12)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
arr.reshape(2, -1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [10]:
arr.reshape(-1, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

# flatten() vs ravel()

Both functions convert a multi-dimensional array into a 1-D array.

flatten()
---------
- Returns a COPY
- Original array remains unchanged

ravel()
-------
- Returns a VIEW whenever possible
- Changes may affect the original array

Shape:
(n,m) ---> (n*m,)

In [11]:
import numpy as np

arr = np.array([[1,2,3],
                [4,5,6]])

arr

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
arr.shape

(2, 3)

In [13]:
arr.flatten()

array([1, 2, 3, 4, 5, 6])

In [14]:
flat = arr.flatten()

flat

array([1, 2, 3, 4, 5, 6])

In [15]:
flat[0] = 100

In [16]:
flat

array([100,   2,   3,   4,   5,   6])

In [17]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
r = arr.ravel()

r

array([1, 2, 3, 4, 5, 6])

In [19]:
r[0] = 100

In [20]:
r

array([100,   2,   3,   4,   5,   6])

In [21]:
arr

array([[100,   2,   3],
       [  4,   5,   6]])

# transpose()

transpose() swaps the axes of an array.

For a 2-D array:

Rows become Columns.

Columns become Rows.

Syntax

arr.T

or

arr.transpose()

In [22]:
import numpy as np

arr = np.array([[1,2,3],
                [4,5,6]])

arr

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
arr.shape

(2, 3)

In [24]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [25]:
arr.T.shape

(3, 2)

# resize()

resize() changes the actual size of the array.

Unlike reshape(),

• Number of elements CAN change.
• Data may be repeated.
• Data may be removed.

Syntax

np.resize(array, new_shape)

In [26]:
import numpy as np

arr = np.array([1,2,3,4])

arr

array([1, 2, 3, 4])

In [27]:
np.resize(arr,8)

array([1, 2, 3, 4, 1, 2, 3, 4])

In [28]:
np.resize(arr,10)

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2])

In [29]:
np.resize(arr,2)

array([1, 2])

In [30]:
np.resize(arr,(2,3))

array([[1, 2, 3],
       [4, 1, 2]])

# concatenate()

concatenate() joins two or more arrays into a single array.

Syntax

np.concatenate((arr1, arr2), axis=0)

Important:
- Arrays must have compatible shapes.
- You can join along rows or columns.
- Controlled using the axis parameter.

In [31]:
import numpy as np

arr1 = np.array([1,2,3])

arr2 = np.array([4,5,6])

In [32]:
np.concatenate((arr1, arr2))

array([1, 2, 3, 4, 5, 6])

In [33]:
arr1 = np.array([[1,2],
                 [3,4]])

arr2 = np.array([[5,6],
                 [7,8]])

In [34]:
np.concatenate((arr1, arr2), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [35]:
np.concatenate((arr1, arr2), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

# stack()

stack() joins arrays by creating a NEW AXIS.

Unlike concatenate(),

• concatenate() joins along an existing axis.
• stack() creates a completely new dimension.

Syntax

np.stack((arr1, arr2), axis=0)

In [36]:
import numpy as np

arr1 = np.array([1,2,3])

arr2 = np.array([4,5,6])

In [37]:
np.concatenate((arr1,arr2))

array([1, 2, 3, 4, 5, 6])

In [38]:
np.stack((arr1,arr2))

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
np.stack((arr1,arr2),axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [40]:
a = np.stack((arr1,arr2),axis=0)

b = np.stack((arr1,arr2),axis=1)

print(a.shape)

print(b.shape)

(2, 3)
(3, 2)


# Specialized Stacking Functions

vstack()       -> Vertical Stack
hstack()       -> Horizontal Stack
column_stack() -> Stack as columns
dstack()       -> Stack along depth (3rd dimension)

These are convenience functions built on the idea of stacking arrays.

In [41]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [43]:
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [44]:
np.dstack((a,b))

array([[[1, 4],
        [2, 5],
        [3, 6]]])

# split()

split() divides one array into multiple smaller arrays.

Syntax

np.split(array, sections)

Related Functions

np.vsplit()
np.hsplit()

Important:
• The array must be divisible into equal parts.
• Otherwise NumPy raises an error.

In [1]:
import numpy as np

arr = np.array([1,2,3,4,5,6])

arr

array([1, 2, 3, 4, 5, 6])

In [2]:
np.split(arr,2)

[array([1, 2, 3]), array([4, 5, 6])]

In [3]:
np.split(arr,3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [4]:
np.split(arr,[2,5])

[array([1, 2]), array([3, 4, 5]), array([6])]

In [5]:
arr = np.array([[1,2],
                [3,4],
                [5,6],
                [7,8]])

In [6]:
np.vsplit(arr,2)

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]])]

In [7]:
arr = np.array([[1,2,3,4],
                [5,6,7,8]])

In [8]:
np.hsplit(arr,2)

[array([[1, 2],
        [5, 6]]),
 array([[3, 4],
        [7, 8]])]

In [9]:
arr = np.array([1,2,3,4,5])

np.array_split(arr, 2)

[array([1, 2, 3]), array([4, 5])]

# append(), insert(), delete()

append()
--------
Adds element(s) at the end.

insert()
--------
Adds element(s) at a specified position.

delete()
--------
Removes element(s) from an array.

Important:
These functions DO NOT modify the original array.
They return a NEW array.

In [10]:
import numpy as np

arr = np.array([10,20,30])

arr

array([10, 20, 30])

In [12]:
new_arr = np.append(arr,40)

print(new_arr)

print(arr)

[10 20 30 40]
[10 20 30]


In [13]:
np.append(arr,[40,50,60])

array([10, 20, 30, 40, 50, 60])

In [14]:
arr = np.array([10,20,30])

In [15]:
np.insert(arr,1,99)

array([10, 99, 20, 30])

In [16]:
np.insert(arr,2,[100,200])

array([ 10,  20, 100, 200,  30])

In [17]:
print(arr)

[10 20 30]


In [18]:
arr = np.array([10,20,30,40])

np.delete(arr,2)

array([10, 20, 40])

In [19]:
np.delete(arr,[0,3])

array([20, 30])

In [20]:
arr = np.array([[1,2],
                [3,4]])

In [21]:
np.append(arr,
          [[5,6]],
          axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [22]:
np.append(arr,
          [[5],[6]],
          axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

# 1. 
| flatten()          | ravel()                          |
| ------------------ | -------------------------------- |
| Returns Copy       | Returns View (whenever possible) |
| Original unchanged | Original may change              |
| More memory        | Less memory                      |
| Slightly slower    | Slightly faster                  |


# 2.
Ravel is better, it does not create a new copy of array and saves memory.

# 3. 

Flatten is safer.


# 4.
| reshape()                                                            | transpose()                                          |
| -------------------------------------------------------------------- | ---------------------------------------------------- |
| Changes the arrangement while keeping the reading order of elements. | Swaps axes (rows become columns).                    |
| Shape changes based on the new dimensions you specify.               | Shape changes by reversing the axes for a 2-D array. |


# 5.
| reshape()                         | resize()                      |
| --------------------------------- | ----------------------------- |
| Number of elements stays the same | Number of elements can change |
| Rearranges data                   | May repeat or remove data     |
| Used frequently in ML             | Rarely used for ML datasets   |


# 6.
| concatenate()                           | stack()                        |
| --------------------------------------- | ------------------------------ |
| Joins along an existing axis            | Creates a new axis             |
| Shape grows along an existing dimension | Number of dimensions increases |
