# Notebook 5: Mathematical Operations & Statistical Functions

In this notebook, we will learn how to perform mathematical, statistical, rounding, logarithmic, exponential, and trigonometric operations using NumPy.

Topics Covered:
- Arithmetic Operations
- Universal Functions (ufuncs)
- Aggregation Functions
- Rounding Functions
- Logarithmic & Exponential Functions
- Trigonometric Functions

# Universal Functions (ufuncs)

A Universal Function (ufunc) is a function that performs
element-wise operations on NumPy arrays.

Examples

np.add()
np.subtract()
np.multiply()
np.divide()
np.sqrt()
np.power()

Why use ufuncs?

• Fast
• Memory efficient
• Works directly on arrays
• Implemented in optimized C code

In [74]:
import numpy as np

marks = np.array([80,75,92,60,88])

marks + 5

array([85, 80, 97, 65, 93])

In [75]:
a = np.array([1,2,3])

b = np.array([10,20,30])

a + b

array([11, 22, 33])

In [76]:
a = np.array([2,4,6])
b = np.array([1,3,5])

print(a + b)

[ 3  7 11]


# np.add()

np.add() performs element-wise addition.

Syntax

np.add(array1, array2)

It is equivalent to using the + operator on NumPy arrays.

In [77]:
import numpy as np

a = np.array([1,2,3])

b = np.array([4,5,6])

np.add(a,b)

array([5, 7, 9])

In [78]:
a+b

array([5, 7, 9])

In [79]:
np.add(a,10)

array([11, 12, 13])

In [80]:
np.add(a,2.5)

array([3.5, 4.5, 5.5])

In [81]:
np.subtract(a, b)

array([-3, -3, -3])

In [82]:
import numpy as np

a = np.array([10,20,30])
b = np.array([1,2,3])

np.subtract(a,b)

array([ 9, 18, 27])

In [83]:
np.multiply(a,b)

array([10, 40, 90])

In [84]:
np.divide(a,b)

array([10., 10., 10.])

In [85]:
np.divide(a,0)

C:\Users\Administrator\AppData\Local\Temp\ipykernel_9952\2104493827.py:1: RuntimeWarning: divide by zero encountered in divide
  np.divide(a,0)


array([inf, inf, inf])

In [86]:
np.power(a,2)

array([100, 400, 900])

In [87]:
a = np.array([10,21,35])

np.mod(a,2)

array([0, 1, 1])

# Aggregation Functions

Aggregation functions combine multiple values into a single value.

Examples

np.sum()
np.mean()
np.min()
np.max()
np.std()
np.var()

Why are they important?

• Data Analysis
• Machine Learning
• Statistics
• Feature Engineering

# np.sum()

Returns the sum of all elements.

Syntax

np.sum(array)

In [88]:
import numpy as np

marks = np.array([80,70,90,60,100])

np.sum(marks)

np.int64(400)

In [89]:
arr = np.array([[1,2],
                [3,4]])

np.sum(arr)

np.int64(10)

In [90]:
arr = np.array([[1,2],
                [3,4]])

np.sum(arr, axis=0)

array([4, 6])

In [91]:
np.sum(arr, axis=1)

array([3, 7])

# np.mean()

Returns the arithmetic average of the elements.

Formula

Mean = Sum of all elements / Number of elements

Syntax

np.mean(array)

In [92]:
import numpy as np

marks = np.array([80,70,90,60,100])

np.mean(marks)

np.float64(80.0)

In [93]:
arr = np.array([[1,2],
                [3,4]])

np.mean(arr)

np.float64(2.5)

In [94]:
arr = np.array([[1,2],
                [3,4]])

np.mean(arr, axis=0)

array([2., 3.])

In [95]:
np.mean(arr, axis=1)

array([1.5, 3.5])

# np.median()

Returns the middle value of the sorted data.

Mean ≠ Median

Mean
-----
Average of all values.

Median
-------
Middle value after sorting.

Median is less affected by extreme values (outliers).

In [96]:
import numpy as np

arr = np.array([20,22,21,23,500])

np.median(arr)

np.float64(22.0)

In [97]:
arr = np.array([10,20,30,40])

In [98]:
np.median([10,20,30,40])

np.float64(25.0)

In [99]:
arr = np.array([[1,2],
                [3,4]])

np.median(arr)

np.float64(2.5)

In [100]:
arr = np.array([[1,5],
                [3,7],
                [9,2]])

np.median(arr, axis=0)

array([3., 5.])

In [101]:
np.median(arr, axis=1)

array([3. , 5. , 5.5])

# Minimum and Maximum Functions

np.min()
---------
Returns the smallest value.

np.max()
---------
Returns the largest value.

np.argmin()
------------
Returns the index of the smallest value.

np.argmax()
------------
Returns the index of the largest value.

In [102]:
import numpy as np

arr = np.array([10,25,5,40,18])

np.min(arr)

np.int64(5)

In [103]:
np.max(arr)

np.int64(40)

In [104]:
np.argmin(arr)

np.int64(2)

In [105]:
np.argmax(arr)

np.int64(3)

In [106]:
arr = np.array([[1,8],
                [5,4]])

In [107]:
np.max(arr)

np.int64(8)

In [108]:
np.min(arr)

np.int64(1)

In [109]:
np.max(arr, axis=0)

array([5, 8])

In [110]:
np.max(arr, axis=1)

array([8, 5])

In [111]:
arr = np.array([10,50,30,50])

In [112]:
np.argmax(arr)

np.int64(1)

# Standard Deviation and Variance

Variance
--------
Measures how spread out the data is.

Standard Deviation
------------------
Square root of the variance.

Small std → Data is close to the mean.
Large std → Data is spread out.

In [113]:
import numpy as np

arr = np.array([10,20,30,40,50])

np.var(arr)

np.float64(200.0)

In [114]:
np.std(arr)

np.float64(14.142135623730951)

In [115]:
a = np.array([49,50,51,50,50])

print(np.std(a))

0.6324555320336759


In [116]:
b = np.array([10,90,20,80,50])

print(np.std(b))

31.622776601683793


In [117]:
arr = np.array([[1,2],
                [3,4]])

In [118]:
np.std(arr)

np.float64(1.118033988749895)

In [119]:
np.std(arr, axis=0)

array([1., 1.])

In [120]:
np.std(arr, axis=1)

array([0.5, 0.5])

# Product and Cumulative Functions

np.prod()
----------
Returns the product of all elements.
Think of it as the multiplication version of sum().

np.cumsum()
------------
Returns cumulative (running) sum.

np.cumprod()
-------------
Returns cumulative (running) product.

In [121]:
import numpy as np

arr = np.array([2,3,4])

np.prod(arr)

np.int64(24)

In [122]:
arr = np.array([[1,2],
                [3,4]])

np.prod(arr)

np.int64(24)

In [123]:
np.prod(arr, axis=0)

array([3, 8])

In [124]:
np.prod(arr, axis=1)

array([ 2, 12])

In [125]:
arr = np.array([10,20,30,40])

np.cumsum(arr)

array([ 10,  30,  60, 100])

In [126]:
arr = np.array([2,3,4])

np.cumprod(arr)

array([ 2,  6, 24])

# Rounding Functions

np.round()
np.floor()
np.ceil()
np.trunc()

Used to round decimal values in different ways.

In [127]:
arr = np.array([2.3, 2.7, -2.3, -2.7])

In [128]:
np.round(arr)

array([ 2.,  3., -2., -3.])

In [129]:
arr = np.array([2.3456, 8.1293])

np.round(arr, 2)

array([2.35, 8.13])

In [130]:
arr = np.array([2.3, 2.7, -2.3, -2.7])
np.floor(arr)

array([ 2.,  2., -3., -3.])

In [131]:
np.ceil(arr)

array([ 3.,  3., -2., -2.])

In [132]:
np.trunc(arr)

array([ 2.,  2., -2., -2.])

# Exponential and Logarithmic Functions

NumPy provides mathematical functions like

np.exp()
np.log()
np.log2()
np.log10()

These are widely used in mathematics,
statistics and machine learning.

In [133]:
import numpy as np

np.exp(1)

np.float64(2.718281828459045)

In [134]:
np.exp(2)

np.float64(7.38905609893065)

In [135]:
np.log(np.exp(2))

np.float64(2.0)

In [136]:
np.log10(1000)

np.float64(3.0)

In [137]:
np.log2(16)

np.float64(4.0)

# Trigonometric Functions

NumPy provides trigonometric functions.

np.sin()
np.cos()
np.tan()

Important:
These functions expect angles in **radians**, not degrees.

Useful conversion functions:

np.deg2rad()
np.rad2deg()

In [138]:
import numpy as np

np.deg2rad(90)

np.float64(1.5707963267948966)

In [139]:
np.sin(np.deg2rad(90))

np.float64(1.0)

In [140]:
np.sin(np.deg2rad(30))

np.float64(0.49999999999999994)

In [141]:
np.cos(np.deg2rad(60))

np.float64(0.5000000000000001)

In [142]:
np.tan(np.deg2rad(45))

np.float64(0.9999999999999999)

In [143]:
np.rad2deg(np.pi)

np.float64(180.0)

In [144]:
np.sin(np.deg2rad(90))

np.float64(1.0)