# NumPy Notebook 6

# Linear Algebra with NumPy

## Topics Covered

- What is Linear Algebra?
- Scalars
- Vectors
- Matrices
- Tensors
- Matrix Multiplication
- Dot Product
- Inverse
- Determinant
- Rank
- Trace
- Solving Linear Equations
- Eigenvalues (Introduction)

---

## Why Learn Linear Algebra?

Linear Algebra is the mathematical language of Machine Learning.

Almost every ML algorithm uses matrices internally.

Examples:
- Linear Regression
- Logistic Regression
- PCA
- Neural Networks
- Computer Vision

# Topic 1 - Scalar

## What is a Scalar?

A scalar is a **single numerical value**.

It has:
- No direction
- No rows or columns
- No dimensions to navigate

Examples:
- 5
- -10
- 3.14
- 100

A scalar represents only one quantity.

In NumPy, a scalar is represented as a **0-dimensional array**.

In [1]:
import numpy as np

scalar = np.array(10)

print(scalar)

10


In [2]:
print(type(scalar))

<class 'numpy.ndarray'>


In [3]:
print(scalar.ndim)

0


In [4]:
print("Shape :", scalar.shape)
print("Size  :", scalar.size)
print("Datatype :", scalar.dtype)

Shape : ()
Size  : 1
Datatype : int64


# Topic 2 - Vector

## What is a Vector?

A vector is a collection of values arranged along a **single axis**.

Unlike a scalar, a vector stores multiple values.

Examples:

[10, 20, 30]

[5, 8, 12, 15]

Characteristics

- Has one dimension
- Stores multiple values
- Shape = (n,)
- ndim = 1

In NumPy, a vector is simply a **1D array**.

In [5]:
import numpy as np

vector = np.array([10, 20, 30, 40, 50])

print(vector)

[10 20 30 40 50]


In [6]:
print(type(vector))
print(vector.ndim)
print(vector.shape)
print(vector.size)
print(vector.dtype)

<class 'numpy.ndarray'>
1
(5,)
5
int64


In [7]:
print(vector[0])

print(vector[2])

print(vector[-1])

10
30
50


In [8]:
vector[1] = 100

print(vector)

[ 10 100  30  40  50]


In [11]:
arr = np.array([[10, 20, 30]])
np.shape(arr)


(1, 3)

# Topic 3 - Matrix

## What is a Matrix?

A matrix is a collection of values arranged in **rows and columns**.

Unlike a vector, a matrix has **two dimensions**.

Examples

[
 [1, 2, 3],
 [4, 5, 6]
]

Characteristics

- Two-dimensional
- Has rows and columns
- Shape = (rows, columns)
- ndim = 2

In NumPy, a matrix is simply a **2D array**.

In [12]:
import numpy as np

matrix = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(matrix)

[[10 20 30]
 [40 50 60]]


In [13]:
print(type(matrix))
print(matrix.ndim)
print(matrix.shape)
print(matrix.size)
print(matrix.dtype)

<class 'numpy.ndarray'>
2
(2, 3)
6
int64


In [14]:
print(matrix[0])

[10 20 30]


In [15]:
print(matrix[1,2])

60


In [16]:
matrix[0,1] = 100

print(matrix)

[[ 10 100  30]
 [ 40  50  60]]
