# Numpy basics

In [1]:
import numpy as np
print(np.__version__)

2.5.0


# NumPy Fundamentals

NumPy (Numerical Python) is the fundamental library used for numerical computing in Python.

It provides:

- Fast multidimensional arrays
- Mathematical operations
- Matrix computations
- Linear algebra
- Random number generation
- Foundation for Machine Learning, Data Science and Deep Learning

Almost every AI library (Pandas, Scikit-Learn, TensorFlow, PyTorch) internally uses NumPy.

## Why not Python Lists?

Python lists are flexible but slow for numerical computation.

NumPy arrays:

- consume less memory
- execute faster
- support vectorized operations
- are optimized using C

## Creating a NumPy Array

The np.array() function is used to create a NumPy array from Python lists.

Syntax:

np.array(iterable)

In [2]:
import numpy as np
arr = np.array([10,20,20,40])
print(arr)

[10 20 20 40]


In [3]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([1.5,2.5,3.5])
arr3 = np.array(["Apple, Banana, Mango"])
arr4 = np.array([True, False, True])

print(arr1)
print(arr2)
print(arr3)
print(arr4)

[1 2 3]
[1.5 2.5 3.5]
['Apple, Banana, Mango']
[ True False  True]


# Array Attributes

Every NumPy array stores metadata (information about the array).

Array attributes help us understand:

- Number of dimensions
- Shape of the array
- Total number of elements
- Data type of elements
- Memory occupied by each element
- Total memory occupied by the array

These attributes are useful for debugging, data analysis, and Machine Learning.

In [4]:
import numpy as np

arr = np.array([[10, 20, 30],
                [40, 50, 60]])

print(arr)

[[10 20 30]
 [40 50 60]]


## ndim

`ndim` returns the number of dimensions (axes) of an array.

Examples:

- 1D array → ndim = 1
- 2D array → ndim = 2
- 3D array → ndim = 3

In [5]:
print(arr.ndim)

2


## shape

`shape` returns the size of each dimension.

Output is returned as a tuple.

For a 2D array:

(rows, columns)

In [6]:
print(arr.shape)

(2, 3)


## size

`size` returns the total number of elements present in the array.

In [7]:
print(arr.size)

6


## dtype

`dtype` returns the data type of the elements stored in the array.

In [8]:
print(arr.dtype)

int64


## itemsize

`itemsize` returns the memory occupied by one element (in bytes).

In [9]:
print(arr.itemsize)

8


## nbytes

`nbytes` returns the total memory occupied by the array.

Formula:

Total Memory = size × itemsize

In [10]:
print(arr.nbytes)

48


In [11]:
import numpy as np

arr = np.array([[10, 20, 30],
                [40, 50, 60]])

print("Dimensions :", arr.ndim)
print("Shape      :", arr.shape)
print("Size       :", arr.size)
print("Data Type  :", arr.dtype)
print("Item Size  :", arr.itemsize)
print("Total Bytes:", arr.nbytes)

Dimensions : 2
Shape      : (2, 3)
Size       : 6
Data Type  : int64
Item Size  : 8
Total Bytes: 48
